# Generated by Django 5.0.11 on 2025-01-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="wtKlientBankTemp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NumDoc", models.CharField(max_length=20)),
                ("Date", models.DateTimeField()),
                ("Summa", models.DecimalField(decimal_places=2, max_digits=10)),
                ("MfoA", models.CharField(max_length=9)),
                ("NaznP", models.CharField(max_length=200)),
                ("service_old", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
