# Generated by Django 5.0.11 on 2025-03-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_wtklientbanktemp_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="refCity",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("net", models.BooleanField(blank=True)),
                ("type", models.IntegerField()),
                ("postindex", models.IntegerField(blank=True)),
                (
                    "connect_tarif",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("name_ukr", models.CharField(blank=True, max_length=50)),
                ("name_ii", models.CharField(max_length=250)),
            ],
            options={
                "db_table": "refCity",
                "db_tablespace": "Bill",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="refHouse",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("region", models.IntegerField()),
                ("street", models.IntegerField()),
                ("house", models.CharField(max_length=50)),
                ("h_type", models.IntegerField(blank=True)),
                ("zip", models.CharField(max_length=6)),
                ("floors", models.IntegerField(blank=True)),
                ("subfloor", models.IntegerField(blank=True)),
                ("topfloor", models.IntegerField(blank=True)),
                ("techfloor", models.IntegerField(blank=True)),
                ("entrances", models.IntegerField(blank=True)),
                ("tp", models.IntegerField(blank=True)),
                ("tp_s", models.IntegerField(blank=True)),
                ("maintainer", models.IntegerField(blank=True)),
                ("map_url", models.CharField(blank=True, max_length=250)),
                ("region2", models.IntegerField(blank=True)),
                ("nflats", models.IntegerField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("net", models.BooleanField(blank=True)),
                ("hide", models.BooleanField(blank=True)),
                (
                    "connect_tarif",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "db_table": "refHouse",
                "db_tablespace": "Bill",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="refLocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("house", models.IntegerField()),
                ("type", models.IntegerField()),
                ("flr", models.IntegerField(blank=True)),
                ("entrance", models.CharField(blank=True, max_length=20)),
                ("room", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "connect_tarif",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "db_table": "refLocation",
                "db_tablespace": "Bill",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="refStreet",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("city", models.IntegerField()),
                ("keyname", models.CharField(max_length=50)),
                ("fullname", models.CharField(max_length=100)),
                ("oldname", models.CharField(blank=True, max_length=100)),
                ("net", models.BooleanField(blank=True)),
                ("type", models.IntegerField()),
                ("oldcity", models.IntegerField(blank=True)),
                (
                    "connect_tarif",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("keyname_ukr", models.CharField(blank=True, max_length=50)),
                ("keyname_ii", models.CharField(max_length=250)),
            ],
            options={
                "db_table": "refStreet",
                "db_tablespace": "Bill",
                "managed": False,
            },
        ),
    ]
