# Generated by Django 5.0.11 on 2025-03-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_refcity_refhouse_reflocation_refstreet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refklientbankstatus",
            options={"managed": False},
        ),
    ]
