# Generated by Django 5.0.11 on 2025-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_refklientbankstatus_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="refClient",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("dt0", models.DateTimeField()),
                ("dt1", models.DateTimeField()),
                ("keyname", models.CharField(max_length=100)),
                ("fullname", models.CharField(max_length=500)),
                ("location", models.IntegerField()),
                ("grp", models.IntegerField()),
                ("type", models.IntegerField()),
                ("paymenttype", models.IntegerField()),
                ("max_credit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("saccount", models.CharField(max_length=6)),
                ("spwd", models.CharField(max_length=50)),
                ("rtxid", models.IntegerField(blank=True)),
                ("dctype", models.IntegerField(blank=True)),
                ("curstate", models.IntegerField()),
                ("i_usr", models.CharField(max_length=128)),
                ("i_dt", models.DateTimeField()),
                ("c_usr", models.CharField(max_length=128)),
                ("c_dt", models.DateTimeField(blank=True)),
                ("lawlocation", models.IntegerField(blank=True)),
                ("postlocation", models.IntegerField(blank=True)),
                ("gen_invoice", models.IntegerField(blank=True)),
                ("npwd", models.IntegerField(blank=True)),
                ("beznal", models.IntegerField(blank=True)),
                ("mode", models.IntegerField(blank=True)),
                ("keyname_ukr", models.CharField(max_length=100)),
                ("talk_lang", models.IntegerField()),
                ("num_rings", models.IntegerField(blank=True)),
                ("last_ring", models.DateTimeField(blank=True)),
                ("last_lk_dt", models.DateTimeField(blank=True)),
                ("last_lk_ip", models.IntegerField(blank=True)),
            ],
            options={
                "db_table": "refClient",
                "db_tablespace": "Bill",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="wtklientbanktemp",
            name="NameB",
            field=models.CharField(default="ДНIПРО.ТВ ТОВ", max_length=50),
        ),
        migrations.AlterModelTable(
            name="refklientbankstatus",
            table="refKlientBankStatus",
        ),
    ]
