# Generated by Django 5.0.11 on 2025-05-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_refclient_wtklientbanktemp_nameb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtklientbanktemp',
            name='service_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
