# Generated by Django 5.0.11 on 2025-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_wtklientbanktemp_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtklientbanktemp',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
